### ISSUE TITLE
Unable to set unsafe message

### ISSUE THREAD

**Issue by geekjuice** [bbatliner/vex-dialog#5]
It seems like because of [these defaults](https://github.com/bbatliner/vex-dialog/blob/master/src/vex.dialog.js#L205-L220), `message` will never be empty when using `vex.dialog.*` because of [this merge](https://github.com/bbatliner/vex-dialog/blob/master/src/vex.dialog.js#L128). The result is the `unsafeMessage` option is ignored unless a falsy `message` is also passed.

``` js
vex.dialog.alert({
  unsafeMessage: '<h1>Danger!</h1>'
});

// Outputs "Alert"

vex.dialog.alert({
  unsafeMessage: '<h1>Danger!</h1>',
  message: null
});

// Outputs formatted "Danger"
```

Is this the intended behavior for this option? I looked at the PR that added this change it didn't document anything about needing to pass a falsy `message` option.

**Comment by bbatliner** [comment]
No, that's not intended, and I'm glad you brought it up. More specifically, the code gets tripped up at [these lines](https://github.com/bbatliner/vex-dialog/blob/9b6eb3af585185f8fcfe3b56b6377d6135cdc0b1/src/vex.dialog.js#L67-L71), which say that unsafe message will be used if and only if a message is not also present. It's this way because it seemed safe at the time to always prioritize using safe content rather than unsafe content.

I think the best solution is to get rid of those defaults. I mean, when are you ever going to call `vex.dialog.alert()` with no arguments, and do you expect a meaningful dialog to appear, anyway? Then we can avoid this option-bludgeoning situation that you pointed out, and still keep the behavior of "if you provide a `message` and `unsafeMessage`, we'll go safe by default."

**Comment by geekjuice** [comment]
Sounds good 👍 

Thanks for the update!

**Comment by bbatliner** [comment]
Alright we should be good to go!
